### PR TITLE
updated vertx and kafka libs to latest stable versions

### PR DESCRIPTION
**Pull request by jtruelove**
I ran the integration tests and bumped the minor version.

### CODE REVIEW

**Comment by jtruelove** [comment]
did this change not get merged?

**Comment by SaschaMoellering** [comment]
Hi,

not yet, because we want to understand why you completely removed the option of providing a partition from outside? We would appreciate to have both options working, so we don't break the existing API.

Thx,
Sascha

**Comment by jtruelove** [comment]
hmm this change was just updating the libraries to latest... what do you mean 'why you completely removed the option of providing a partition from outside' unless I'm missing something here.

**Comment by SaschaMoellering** [comment]
Sorry, my fault, wrong PR :/

**Comment by jtruelove** [comment]
np

**Pull request merged**
