### PR TITLE
Fix issue mod-kafka#10: Partition key is defined with the message to be ...

### PR DESCRIPTION
**Pull request by bnouyrigat**
The partition key should not be part of the configuration, but a value
which may depend on the message to be sent.

### CODE REVIEW

**Comment by SaschaMoellering** [comment]
Thanks for contributing

**Comment by SaschaMoellering** [comment]
Hi, 

quick question: can we implement the old behaviour as well, because we don't want to break the API.

**Comment by bnouyrigat** [comment]
I'm not sure to understand: If a partition key is not set when the message is sent, you want a default key is used, and the default partition key is configurable ?

**Comment by SaschaMoellering** [comment]
Yes exactly, this would be great.

**Pull request merged**
